excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://rika-moniker.github.io
title: Kindle Time Traveller
tagline: Reviews of New Literature
description: Hi, my name's Rika and I'm an engineering student. But, in my spare time, I'm a Kindle addict, who greedily sucks up all the new and lesser-known literature that comes out constantly, mostly from the Indie writing scene. Here, I'll try to share reviews of the books uncovered by the mainstream, in order to give compulsive readers, like me, an alternative place to look to fulfill our Kindle addictions. :)
paginate: 5